// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFM3Hxr7tkWDmHPdTs8Y878k8IJ_r1BuM',
    appId: '1:276157245463:web:716608794d4caa72ed9452',
    messagingSenderId: '276157245463',
    projectId: 'bananagram-8ebfd',
    authDomain: 'bananagram-8ebfd.firebaseapp.com',
    storageBucket: 'bananagram-8ebfd.firebasestorage.app',
    measurementId: 'G-V82FETT5VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASPcaPj4MKF31SrqgKzhK4-6qMZ2WGs9E',
    appId: '1:276157245463:android:61ad93d470620e06ed9452',
    messagingSenderId: '276157245463',
    projectId: 'bananagram-8ebfd',
    storageBucket: 'bananagram-8ebfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk8hwv2Y8YrETRr7xUDXi_Nc2I3bIS8r8',
    appId: '1:276157245463:ios:97380586bb373eeced9452',
    messagingSenderId: '276157245463',
    projectId: 'bananagram-8ebfd',
    storageBucket: 'bananagram-8ebfd.firebasestorage.app',
    iosBundleId: 'com.example.bananagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk8hwv2Y8YrETRr7xUDXi_Nc2I3bIS8r8',
    appId: '1:276157245463:ios:97380586bb373eeced9452',
    messagingSenderId: '276157245463',
    projectId: 'bananagram-8ebfd',
    storageBucket: 'bananagram-8ebfd.firebasestorage.app',
    iosBundleId: 'com.example.bananagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFM3Hxr7tkWDmHPdTs8Y878k8IJ_r1BuM',
    appId: '1:276157245463:web:c712231f4ef3d4b3ed9452',
    messagingSenderId: '276157245463',
    projectId: 'bananagram-8ebfd',
    authDomain: 'bananagram-8ebfd.firebaseapp.com',
    storageBucket: 'bananagram-8ebfd.firebasestorage.app',
    measurementId: 'G-YJZ8TNEQRD',
  );
}
